DATASETS:
  TRAIN: H36M-TRAIN
  VAL: H36M-VAL-P2
GENERAL:
  TOTAL_STEPS: 300000
  LOG_STEPS: 200
  VAL_STEPS: 200
  CHECKPOINT_STEPS: 10000
  NUM_WORKERS: 1
TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 2
  NUM_TEST_SAMPLES: 64
  POSE_2D_NOISE_RATIO: 0.01
  POSE_3D_NOISE_RATIO: 0.005
LOSS_WEIGHTS:
  KEYPOINTS_3D_EXP: 0.0
  KEYPOINTS_3D_MODE: 1.0
  NLL: 0.001
MODEL:
  BACKBONE:
    TYPE: fcresnet
    IN_CHANNELS: 34
    HIDDEN_CHANNELS: 1024
    OUT_CHANNELS: 1024
    NUM_LAYERS: 2
    DROPOUT: TRUE
  FLOW:
    DIM: 48
    NUM_LAYERS: 4
    CONTEXT_FEATURES: 1024
    LAYER_HIDDEN_FEATURES: 1024
    LAYER_DEPTH: 2
  FC_HEAD:
    NUM_FEATURES: 1024