MODE:
  TCMR: True
  TAPE: False
  DISCRIMINATOR: False
  IMG: False
  MOTION_DISCRIMINATOR: False
  EXTRACT: False
DATASETS:
  TRAIN: 
    #3DPW-TRAIN:
    #  WEIGHT: 0.3
    #POSE:
    #  WEIGHT: 1.0
    H36M-TRAIN:
      WEIGHT: 0.7
    MPI-INF-TRAIN:
      WEIGHT: 0.3
    #H36M-TRAIN:
    #  WEIGHT: 0.1
    #MPI-INF-TRAIN:
    #  WEIGHT: 0.1
  VAL:
    3DPW-VAL:
      WEIGHT: 1.0
    #3DPW-VAL:
    #  WEIGHT: 0.7
    #H36M-VAL:
    #  WEIGHT: 0.0
    #MPI-INF-VAL:
    #  WEIGHT: 1.0
  MOCAP: CMU-MOCAP
SMPL:
  MODEL_PATH: data/smpl
  GENDER: neutral
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_EXTRA: data/SMPL_to_J19.pkl
  MEAN_PARAMS: data/smpl_mean_params.npz
GENERAL:
  TOTAL_STEPS: 100000
  LOG_STEPS: 100
  VAL_STEPS: 100
  CHECKPOINT_STEPS: 1000 #10000
  NUM_WORKERS: 12
TRAIN:
  LR: 0.00005 #01 #1e-4
  WEIGHT_DECAY: 0.0
  BATCH_SIZE: 32
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 2
  NUM_TEST_SAMPLES: 1 #64
  POSE_2D_NOISE_RATIO: 0.01
  SMPL_PARAM_NOISE_RATIO: 0.005
LOSS_WEIGHTS:
  KEYPOINTS_3D_EXP: 0.0
  KEYPOINTS_3D_MODE: 0.05
  KEYPOINTS_2D_EXP: 0.001
  KEYPOINTS_2D_MODE: 0.01
  GLOBAL_ORIENT_EXP: 0.000
  GLOBAL_ORIENT_MODE: 0.001
  BODY_POSE_EXP: 0.0
  BODY_POSE_MODE: 0.001
  ORTHOGONAL: 0.1
  BETAS_EXP: 0.0
  BETAS_MODE: 0.005
  #BETAS_MODE: 0.0005
  NLL: 0.001
  ADVERSARIAL: 0.0005
  #ADVERSARIAL: 0.001
MODEL:
  SEQLEN: 1 #6 
  STRIDE: 1 #6 
  IMAGE_SIZE: 224
  IMAGE_MEAN: [0.485, 0.456, 0.406]
  IMAGE_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
    OUT_CHANNELS: 2048
  FLOW:
    DIM: 144
    NUM_LAYERS: 4
    CONTEXT_FEATURES: 2048
    LAYER_HIDDEN_FEATURES: 1024
    LAYER_DEPTH: 2
  FC_HEAD:
    NUM_FEATURES: 1024
EXTRA:
  FOCAL_LENGTH: 5000
  NUM_LOG_IMAGES: 4
  NUM_LOG_SAMPLES_PER_IMAGE: 8
  PELVIS_IND: 39
